// Service Worker for Push Notifications and PWA functionality
/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

// Define NotificationAction interface
interface NotificationAction {
  action: string;
  title: string;
  icon?: string;
}

// Extend NotificationOptions to include missing properties
interface ExtendedNotificationOptions extends NotificationOptions {
  vibrate?: number[];
  actions?: NotificationAction[];
}

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Take control of all pages as soon as the service worker activates
self.skipWaiting();
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Handle push notifications
self.addEventListener("push", (event: PushEvent) => {
  if (!event.data) return;

  const data = event.data.json();

  const options: ExtendedNotificationOptions = {
    body: data.body,
    icon: "/android-chrome-192x192.png",
    badge: "/favicon-32x32.png",
    vibrate: [100, 50, 100],
    data: {
      dateOfArrival: Date.now(),
      primaryKey: data.primaryKey,
      url: data.url || "/",
    },
    actions: [
      {
        action: "view",
        title: "View Details",
        icon: "/favicon-32x32.png",
      },
      {
        action: "dismiss",
        title: "Dismiss",
      },
    ],
  };

  event.waitUntil(self.registration.showNotification(data.title, options));
});

// Handle notification clicks
self.addEventListener("notificationclick", (event: NotificationEvent) => {
  event.notification.close();

  if (event.action === "view") {
    const urlToOpen = event.notification.data.url || "/";

    event.waitUntil(
      self.clients
        .matchAll({ type: "window", includeUncontrolled: true })
        .then((windowClients) => {
          // Check if there is already a window/tab open with the target URL
          for (const client of windowClients) {
            if (client.url === urlToOpen && "focus" in client) {
              return client.focus();
            }
          }
          // If not, open a new window/tab
          if (self.clients.openWindow) {
            return self.clients.openWindow(urlToOpen);
          }
        })
    );
  } else if (event.action === "dismiss") {
    // Just close the notification
    return;
  } else {
    // Default action: open the app
    const urlToOpen = event.notification.data.url || "/";
    event.waitUntil(
      self.clients.openWindow
        ? self.clients.openWindow(urlToOpen)
        : Promise.resolve()
    );
  }
});

export {};